description: Hack the Burgh, the hackathon from beyond the wall, will be returning soon.

sass:
   sourcemap: true

navigation:
  - text: Home
    url: "#top"
  - text: FAQ
    url: "#faq"
  - text: Find us
    url: "#location"
  - text: Sponsors
    url: "#sponsors"