description: Hack the Burgh, the hackathon from beyond the wall, will be returning soon.

sass:
   sourcemap: true

navigation:
  - text: Home
    url: "#top"
  - text: Schedule
    url: "/live/#schedule"
  - text: FAQ
    url: "#faq"
  - text: Participant Handbook
    url: "http://2017.hacktheburgh.com/static/legal/HTB_ParticipantHandbook.pdf"
  - text: Find us
    url: "#location"
  - text: Sponsors
    url: "#sponsors"
